# Site settings
title: Oscar Nordquist
email: oscar.cv.nordquist@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some say that good code comes from those who've practiced the fine art of "the matrix" - 
  But I say no to that - and my words are law.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  NorthernTwig

# Build settings
markdown: kramdown
