# Site settings
title: Oscar Nordquist
email: oscar.cv.nordquist@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Remember this: <br>There's no faster code than no code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://northerntwig.github.io" # the base hostname & protocol for your site
twitter_username: Oscarthisis
github_username:  NorthernTwig


# Build settings
markdown: kramdown
